### ISSUE TITLE
ctrl q not active

### ISSUE THREAD

**Issue by bksubhuti** [linuxdeepin/deepin-editor#57]
ctrl q should close the editor.
Standard linux command is seen as a bug if it is not there.

**Comment by BLumia** [comment]
I didn't see why. Is there a freedesktop standard for the <kbd>Ctrl+Q</kbd> shortcut?

You can always use the setting dialog to config the shortcut to fit your requirement, but I don't think *standard linux command* exists, since linux itself is just a kernel.

**Comment by BLumia** [comment]
addition: QKeySequence actually offered some common shortcut, you can [check out at Qt's documentation here](https://doc.qt.io/archives/qt-4.8/qkeysequence.html#standard-shortcuts). But as you can see it's desktop specific thing, not a standard, and it's not suitable for all kinds of applications (most terminal emulator use <kbd>Ctrl+Shift+C</kbd> for copying text, for example).

So we suggest you config the shortcuts in setting dialog :)

**Comment by bksubhuti** [comment]
Perhaps we can call it a feature request.
A  sampling of apps on my computer  have ctrl q   inkscape, gimp, libreoffice writer, synaptic,nautilus, gedit, vlc, ardour, Firefox, Calibre, Sigil .. EVEN Visual Code (by microsoft).
As far as I remember all ubuntu flavour apps have ctrl+q to quit

Chrome, No
Deepin apps No

In the 90's when I was trying to become a microsoft certified programmer, I needed to pass 2 exams in win arch which is a philosophy about how windows should be consistent and programmed to have all of these standards.  For them it is alt+f4

ctrl c and ctrl v are standards.  The only reason terminal uses ctrl+shift c is because it would conflict with quitting a  program from pre-windows days.  Elementary actually has a clever ctrl+c ctrl+v allowance wihthout the need for shift.. THAT IS SO COOL.

Ctrl +f is a standard too.  I didn't see that issue rejected on the app store.

You can decide who your users are coming from and how familiar you want to be for them.  My guess is Ubuntu and Eos are your main audience.  I mostly come from Ubuntu Mate and eOS

**Comment by BLumia** [comment]
I can understand about there are user comfortable with <kbd>Ctrl+Q</kbd> to do quit, in fact a lot of DDE user comes from Windows which doesn't use <kbd>Ctrl+Q</kbd> to quit application, pressing such shortcut makes app quit may make these user confused. Since user may able to config the shortcut by user itself, so maybe it's not a big deal for this.

Anyway let's reopen this issue and see if we can change the default keybinding :)

cc @wangjia12

**Comment by bksubhuti** [comment]
Good questions to ask in the design room are:  
Is there a default keybinding to close the app? 
**If there is not a keybinding to quit, what should it be?**
How difficult is it to add a keybinding :) ?  
If one is using qt for dev, should one use the qt specification?
Where do the majority of Deepin OS users come from?
What do Mint, eOS, and official Ubuntu flavors use which make up the majority of Linux Users (excluding chrome and android)?

I can easily add this myself as you say, but I'm trying to be a contributor to the deepin os.  I used to be a msvpp programmer in the 90's  but nothing much today.  The appstore has not been commented on either.. Ctrl F is very important and is surely a standard across OS's

**Comment by BLumia** [comment]
Sorry I'm wrong the setting dialog doesn't offer a quit app keybinding setting option, my bad. Product manager may look into this issue later.

----------

I'm not the designer nor the product manager, but still would like try to answer the questions, correct me if I wrong :)

> Is there a default keybinding to close the app?

<kbd>Alt+F4</kbd> I guess. It's a window manager side concept.

How difficult is it to add a keybinding :) ?

There is a `settings.json` in the resource file, edit the json and add a keybinding, then you can use the config value in the application. You can take other config value as reference and it can be easy to add :)

> If one is using qt for dev, should one use the qt specification?

If there is a freedesktop spec, try follow that spec.

> Where do the majority of Deepin OS users come from?

For non-community editon (Pro) it's Windows.

> What do Mint, eOS, and official Ubuntu flavors use

Not sure but I guess maybe it's because most of them are based on / forked from GNOME and their guideline use <kbd>Ctrl+Q</kbd> as the common quit app keybinding?

**Comment by bksubhuti** [comment]
Well I did notice that ALT + F4 did work and that I can change the key bindings to CTRL+Q
I guess that is good that there is a version that attracts users from Windows.
I would be interested to see what the management meeting outcome was.

**Comment by z966768** [comment]
PM said that we do not need ctrl+q because we all use alt+f4.
